name: example
description: An example project to show the usage of fab_circular_menu package.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  fab_circular_menu:
    path: ./../

flutter:
  uses-material-design: true